### PR TITLE
Add support for Riak CS Control

### PR DESCRIPTION
**Pull request by hectcastro**
Adding Riak CS Control support to this project consists of the following:
- [x] A merge of the [pull request](https://github.com/hectcastro/chef-riak-cs-create-admin-user/pull/1) against the [riak-cs-create-admin-user](https://github.com/hectcastro/chef-riak-cs-create-admin-user) cookbook
- [x] A merge of the [pull request](https://github.com/basho/riak-cs-chef-cookbook/pull/15) against the [riak-cs](https://github.com/basho/riak-cs-chef-cookbook) cookbook

This pull request can be tested as is. After the PRs are merged, references to `riak-cs-control` branches in the `Berksfile` need to be removed.

### CODE REVIEW

**Comment by cheeseplus** [comment]
Any reason this wasn't implemented as a recipe for the riak-cs cookbook?

**Comment by hectcastro** [comment]
Good point. I separated them because `riak-cs-control` is a separate package, but `stanchion` is also a separate package, so this should be merged into the `riak-cs` cookbook.

I'll re-work this PR and submit one to the `riak-cs-chef-cookbook`.

**Comment by hectcastro** [comment]
PR updated – Riak CS Control support is now achieved through a recipe within the Riak CS cookbook.

**Comment by hectcastro** [comment]
This one is ready to be put to bed.

/cc @cheeseplus @tylerhannan

**Pull request merged**
